# Generated by Django 2.0.7 on 2018-07-22 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField()),
                ('resolved_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('issue_type', models.CharField(choices=[('BUG', 'bug'), ('FEATURE', 'feature')], default='bug', max_length=9)),
                ('status', models.CharField(choices=[('TODO', 'todo'), ('DOING', 'doing'), ('DONE', 'done')], default='todo', max_length=7)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
