# Generated by Django 2.0.7 on 2018-07-24 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20180724_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
