# Generated by Django 2.0.7 on 2018-07-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20180724_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
