# Generated by Django 2.0.7 on 2018-09-03 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_savedissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedissue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
